# Generated by Django 5.2.8 on 2025-11-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('Dept', models.CharField(max_length=25)),
                ('Batch', models.CharField(max_length=25)),
                ('PlayerPhoto', models.ImageField(upload_to='playerPhoto/')),
                ('PlayerRole', models.CharField(max_length=25)),
                ('WicketKeeping', models.BooleanField()),
                ('P_ID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=25)),
                ('TeamHeadManager', models.CharField(max_length=25)),
                ('TeamLogo', models.ImageField(upload_to='teamLogo/')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Dept', models.CharField(max_length=25)),
                ('Batch', models.CharField(max_length=25)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BidTransactions',
            fields=[
                ('price', models.IntegerField()),
                ('T_ID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('playername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.playerdetails')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamdetails')),
            ],
        ),
    ]
