# Generated by Django 5.2.8 on 2025-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdetails',
            name='TeamMarquee',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='teamdetails',
            name='TeamPlayingManager',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='teamdetails',
            name='TeamRetainedPlayer',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
