# Generated by Django 6.0 on 2025-12-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teamdetails_teammarquee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtransactions',
            name='T_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'UnSold'), (2, 'Sold')], default=0),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='WicketKeeping',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
