# Generated by Django 6.0 on 2025-12-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bidtransactions_t_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtransactions',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teamdetails'),
        ),
    ]
