# Generated by Django 6.0 on 2025-12-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bidtransactions_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='PlayerPhoto',
            field=models.URLField(max_length=250),
        ),
    ]
