# Generated by Django 6.0 on 2025-12-29 08:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teamdetails_hm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='PlayerPhoto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='player_photo'),
        ),
    ]
