# Generated by Django 6.0 on 2025-12-29 12:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_playerdetails_playerphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdetails',
            name='TeamLogo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='team_logo'),
        ),
    ]
