# Generated by Django 6.0 on 2026-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teamdetails_teamlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtransactions',
            name='T_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'UnSold'), (2, 'Sold'), (3, 'Retained'), (4, 'Marquee')], default=0),
        ),
        migrations.DeleteModel(
            name='ManagerDetails',
        ),
    ]
